### ISSUE TITLE
Consequences of lengthening TIMEOUT_IDLE?

### ISSUE THREAD

**Issue by greencoder** [djacobs/PyAPNs#117]
Hello,

Thanks for this great project! I appreciate the hard work of everyone involved. I'm trying to get my head around the connection reset and timeout issues to make sure I understand them.

What are the consequences of lengthening the idle timeout from 30 seconds to a longer period like 300 seconds? I'm concerned about a possible scenario where I'm sending one message per minute, each one resulting in a reconnection.

Does the timeout ensure that we know what the status of the connection in case it's reset by Apple?  If it was reset before the timeout window and we tried to write to the socket, what would happen?

**Comment by jimhorng** [comment]
@greencoder ,
Then, it will become #94... :)

**Comment by greencoder** [comment]
@jimhorng Thanks for the quick reply! Hope it wasn't a dumb question, it seems like a pretty thorny problem.

Is it possible to create a thread to test the socket connection every N seconds and just mark it as dead if it's not alive? 

From what I can see, it looks like pyapns does a great job of reconnecting *if* we know the connection is not alive, but knowing that is the challenge because Apple isn't closing the socket in a friendly manner? (they do a reset vs close?)

Please forgive me if these questions have been covered!

**Comment by jimhorng** [comment]
@greencoder ,
From what I observed, APNS did nothing but closed the connection on their side, and I found no good way to test if that connection is still alive, it just hang for some time after...
So the final decision is to close it before it enters that weird state.

**Comment by ExplodingCabbage** [comment]
Sounds like there are a bunch of delicate problems here that have been thoughtfully addressed by @jimhorng with a lot of experimentation to figure out the gotchas. Since there isn't any conrete actionable suggestion here and the conversation seems to have run its course, I'm going to close this, with the proviso that I don't really understand all these connection-management issues and others are welcome to reopen or create new issues if there are still improvements to be made.
