### ISSUE TITLE
AttributeError: 'GatewayConnection' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by piglei** [djacobs/PyAPNs#55]
Hi, I'm testing this package with given demo code, but it raises this excepiton.

```
Press ENTER or type command to continue
Traceback (most recent call last):
  File "test_pyapns.py", line 10, in <module>
    apns.gateway_server.send_notification(token_hex, payload)
  File "/Library/Python/2.7/site-packages/apns.py", line 380, in send_notification
    self.write(self._get_notification(token_hex, payload))
  File "/Library/Python/2.7/site-packages/apns.py", line 173, in write
    return self._connection().write(string)
  File "/Library/Python/2.7/site-packages/apns.py", line 166, in _connection
    self._connect()
  File "/Library/Python/2.7/site-packages/apns.py", line 139, in _connect
    self._socket.settimeout(self.timeout)
AttributeError: 'GatewayConnection' object has no attribute 'timeout'

shell returned 1
```

After looking at the source code, I found there is not default `timeout` attribute on `GatewayConnection` object.

It this a bug or something?

**Comment by ExplodingCabbage** [comment]
Took me a while to track down what this was about, since looking at the current code (as @tim-schilling evidently was) it was clear that the traceback given here was impossible. There was an old version that had this bug, though. It was was fixed on the same day this issue was opened by this commit: https://github.com/djacobs/PyAPNs/commit/9cf5b57fd86c33172ce81107e691e57287a1bcb9

Closing.
